ai_model: "deepseek"
deepseek_api_key: "your-deepseek-api-key-here"
claude_api_key: "your-claude-api-key-here"
gemini_api_key: "your-gemini-api-key-here"
grok_api_key: "your-grok-api-key-here"
ironheart_endpoint: "http://special-ironheart-endpoint"
logging_level: "INFO"
waf_bypass_enabled: true
max_retries: 3
